### ISSUE TITLE
Does this project still work with hhvm?

### ISSUE THREAD

**Issue by danpoltawski** [sebastianbergmann/hhvm-wrapper#20]
Trying the analyze on a php file I get a failure:

```
hhvm-wrapper analyze index.php 
hhvm-wrapper 2.0.0 by Sebastian Bergmann.

Using ruleset /home/danp/.composer/vendor/sebastian/hhvm-wrapper/ruleset.xml

HHVM failed to process the files.
```
My hhvm version:
```
HipHop VM 3.4.0 (rel)
Compiler: tags/HHVM-3.4.0-0-g817b3a07fc4e509ce15635dbc87778e5b3496663
Repo schema: 0e12aaa31fae66b5591f65603de50c9d62caafac
Extension API: 20140829
```

But trying to run the commands manually I get `Unknown target: analyze` and trying to google to work out how to do the static analysis with hhvm I can't find anything at all. Maybe its been superseeded by hack?

**Comment by jdespatis** [comment]
Same problem here. I use this version

```
HipHop VM 3.6.0 (rel)
Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce
```

**Comment by GrahamCampbell** [comment]
> Same problem here. I use this version

As I said, it doesn't work in hhvm anymore. They removed it even before 3.0.0.
